# Recommend creating a .env file in the root directory for these:
# VAULT_VERSION=1.19-ent
# VAULT_LOG_LEVEL=info
# VAULT_PORT=8200

services:
  vault:
    image: hashicorp/vault-enterprise:${VAULT_VERSION:-1.20-ent}
    container_name: ${COMPOSE_PROJECT_NAME}_vault
    restart: unless-stopped
    ports:
      - "${VAULT_PORT:-8200}:8200"
    env_file:
      - .env # Contains VAULT_ADDR, VAULT_LICENSE
    environment:
      VAULT_LOG_LEVEL: ${VAULT_LOG_LEVEL:-info} # Default to 'info', allow override via .env
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/vault/raft.hcl:/vault/config/raft.hcl:ro
      - vault-data:/vault/file  # Need this volume to fudge permissions error
      - vault-logs:/vault/logs
      - ./certs:/vault/certs:ro  # Mount certificates directory
    command: server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8200/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s # Give Vault time to start before checking   
      
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./volumes/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./volumes/grafana/vault_dashboard.json:/var/lib/grafana/dashboards/vault_dashboard.json:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus
      - loki
      
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./volumes/loki/loki.yml:/etc/loki/loki.yml:ro
      - loki-data:/loki/data
      - ./volumes/loki/loki_perm_fix.sh:/loki/loki_perm_fix.sh:ro
#    command: -config.file=/etc/loki/loki.yml
    entrypoint: /loki/loki_perm_fix.sh
    user: root # Required for permission fix as Loki runs as user Loki by default

  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_promtail
    restart: unless-stopped
    volumes:
      - ./volumes/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - promtail-data:/promtail
      - vault-logs:/mnt/vault-logs
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki

  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  loki-data:
  grafana-data:
  prometheus-data:
  promtail-data:
  vault-data:
  vault-logs:
  redis-data:

