version: '3'

dotenv:
  - .env

tasks:
  default:
    aliases: ["all"]
    cmds:
      - task: up
      - task: unseal

  up:
    preconditions:
      - test -f .env
      - test -f podman-compose.yml
      - test -x ./scripts/elk/00_create-certs.sh
      - test -x ./scripts/elk/10_setup-users.sh
    cmds:
      - task: ensure-podman
      - ./scripts/elk/00_create-certs.sh
      - sleep 10
      - podman-compose -f podman-compose.yml up -d
      - sleep 5
      - |
        echo "Grafana: http://localhost:3000"
        echo "Prometheus: http://localhost:9090"
        echo "Vault: http://localhost:8200"
        echo "Redis: http://localhost:6379"
        echo "Elastic: https://localhost:5601"
    silent: true

  vault-up:
    preconditions:
      - test -f .env
      - test -f podman-compose.yml
    cmds:
      - task: ensure-podman
      - podman-compose -f podman-compose.yml up vault -d
      - sleep 5
      - |
        echo "Vault: http://localhost:8200"
    silent: true

  down:
    cmds:
      - task: stop

  restart:
    cmds:
      - podman-compose -f podman-compose.yml restart vault

  status:
    cmds:
      - vault status

  init:
    cmds:
      - ./scripts/00_vault_init.sh

  unseal:
    cmds:
      - ./scripts/20_vault_unseal.sh

  backup:
    cmds:
      - vault operator raft snapshot save backup-`date +"%Y%m%d-%H%M"`.snap

  rm:
    aliases: ["clean"]
    cmds:
      - podman-compose -f podman-compose.yml down -v || true
      - podman container prune -f || true
      - rm -rf certs
      - rm -rf fleet-tokens
    ignore_error: true

  benchmark:
    cmds:
      - vault-benchmark run -config=./benchmark/config.hcl

  metrics:
      cmds:
        - |
          curl -s --header "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/sys/metrics?format=prometheus"
          
  logs-vault:
    cmds:
      - podman-compose -f podman-compose.yml logs -f vault

  logs:
    cmds:
      - podman-compose -f podman-compose.yml logs -f

  stop:
    cmds:
      - podman-compose -f podman-compose.yml stop

  agent-up:
    dir: ./tfc-agent
    preconditions:
      - test -f .env
      - test -f podman-compose.yml
    cmds:
      - podman-compose -f podman-compose.yml up -d

  agent-down:
    dir: ./tfc-agent
    preconditions:
      - test -f .env
      - test -f podman-compose.yml
    cmds:
      - podman-compose -f podman-compose.yml stop

  ui:
    cmds:
      - open http://localhost:8200
      - ./scripts/10_vault_vars.sh

  pull:
    cmds:
      - podman-compose -f podman-compose.yml pull
    silent: true

  dev:
    preconditions:
      - test -f .env
    cmds:
      - task: ensure-podman
      - podman run --rm -p 8200:8200 --cap-add=IPC_LOCK -e VAULT_LICENSE=$VAULT_LICENSE docker.io/hashicorp/vault-enterprise:latest server -dev -dev-root-token-id=root -dev-listen-address="0.0.0.0:8200"
    silent: true

  redis:
    dir: labs/database/redis/
    cmds:
      - source ../../../.env && terraform init -upgrade
      - source ../../../.env && terraform apply -auto-approve

  elk:
    dir: labs/database/elk/
    cmds:
      - source ../../../.env && terraform init -upgrade
      - source ../../../.env && terraform apply -auto-approve

  mfa-duo:
    aliases: ["mfa","duo"]
    dir: labs/mfa/duo/
    cmds:
      - source ../../../.env && terraform init -upgrade
      - source ../../../.env && terraform apply -auto-approve     

  elk-fleet:
    aliases: ["fleet"]
    preconditions:
      - test -x ./scripts/elk/fleet/20_post-deploy-fleet.sh
    vars:
      delay: '{{.delay | default 30}}' # Default is 30 seconds
    cmds:
      - |
        echo "Waiting for containers to stabilise..."
        i={{.delay}}
        while [ $i -ge 0 ]; do
          printf "\rTime remaining: %02ds" "$i"
          sleep 1
          i=$((i-1))
        done
        echo -e "\nStarting Fleet configuration..."
      - ./scripts/elk/fleet/20_post-deploy-fleet.sh

  elk-audit-logs:
    aliases: ["logging", "audit", "audit-logs", "audit-logs-elk"]
    deps: ["elk-fleet"]  # This will run elk-fleet first
    preconditions:
      - test -x ./scripts/elk/fleet/30_vault-elk-integration.sh
    cmds:
      - sleep 60
      - ./scripts/elk/fleet/30_vault-elk-integration.sh
      - sleep 60

  # Helper task to ensure Podman machine is running (macOS)
  ensure-podman:
    aliases: ["podman"]
    desc: "Ensure Podman machine is running (macOS only)"
    cmds:
      - |
        if [[ "$(uname)" == "Darwin" ]]; then
          if ! podman machine list --format json 2>/dev/null | grep -q '"Running": true'; then
            echo "🚀 Starting Podman machine..."
            podman machine start
            echo "✅ Podman machine started successfully"
          else
            echo "✅ Podman machine is already running"
          fi
        fi
    platforms: [darwin]
    internal: true
    silent: true